### PR TITLE
Langput

### PR DESCRIPTION
**Pull request by Polonium8400**

### CODE REVIEW

**Comment by Polonium8400** [comment]
All I added a precursor to localization and all I added was the default English

**Comment by theycallmemac** [comment]
Would advise checking how you're reading user input for the language of choice

**Comment by Polonium8400** [comment]
i will fix the tabs later

**Comment by Polonium8400** [comment]
and langput uses the ; instead of : to recognize input

**Comment by Polonium8400** [comment]
hi guys no description provided

**Comment by theycallmemac** [comment]
I think these changes are just complicating the program somewhat. Math is a pretty universal language. It's probably better to work on a new project instead.

**Comment by Polonium8400** [comment]
Ok so I can close the PR and start a new project?

**Pull request closed without merging**
