### PR TITLE
Fork#1 between classes

### PR DESCRIPTION
**Pull request by Polonium8400**
I've used the ELIF loop to create the UI, and I've added all basic operators plus exponentiation

### CODE REVIEW

**Comment by Polonium8400** [comment]
https://developer.github.com/program/ this is a part of Github I've discovered

**Comment by Polonium8400** [comment]
https://classroom.github.com/ and this

**Comment by theycallmemac** [comment]
Hey Polonium8400. Great work, but there's a few things you need to change before I can merge your request.

Your inputs are structured incorrectly. Instead of lines like:
y = input(float("enter the decided variable for x:")

Try:
y = float(input("enter the decided variable for y:"))

Along with this, some of your elif statements are missing colons after them. Instead of lines like:

elif user_input == "sub"

Try:

elif user_input == "sub":

Once you make these changes here, I'll be able to merge your request :)

**Comment by Polonium8400** [comment]
I checked the code - twice -  and I found no y = (".......x")

**Comment by Polonium8400** [comment]
Also, i updated the ELIF loops with the needed colons

**Comment by Polonium8400** [comment]
https://travis-ci.org/CoderDojoBallaghaderreen/python-projects/builds/306863251?utm_source=github_status&utm_medium=notification and this came up around the all checks failed thing on the pull request stuff

**Comment by theycallmemac** [comment]
I'll show you why your code isn't working with your code at CoderDojo today! :)

**Comment by Polonium8400** [comment]
the lastest commit is ready
👍

**Pull request merged**
