### PR TITLE
evenodd.py

### PR DESCRIPTION
**Pull request by draegast**
not sure if it'll work but i gave it an attempt

### CODE REVIEW

**Comment by draegast** [comment]
thanks, i kinda knew that it was bad and that i was wrong but i didnt know what to add and i did look over the other loops but i didnt know how to apply it to this loop

**Comment by theycallmemac** [comment]
No dude dont worry. We are here to make it better. Leave this open now and check the new issue I create for you and we can come back to this again

**Comment by draegast** [comment]
made a big change, that might be it, not sure

**Comment by draegast** [comment]
a little better but for the loop would we have to introduce I or another thing into it?

**Pull request merged**
